# Generated by Django 3.2 on 2021-04-15 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a4c5c854-9db0-11eb-bdc6-ce2ef2e2a8da'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=6)),
                ('age', models.IntegerField()),
                ('time', models.DateField(auto_now=True)),
            ],
        ),
    ]
